### ISSUE TITLE
iOS sdk 8.3 CCHLinkTextView  Auto property synthesis will not synthesize property error

### ISSUE THREAD

**Issue by eralpkaraduman** [choefele/CCHLinkTextView#10]
Just updated my Xcode to 6.3 and building for iOS 8.3
CCHLinkTextView.h line 41
@property (nonatomic, copy) NSDictionary *linkTextAttributes NS_AVAILABLE_IOS(7_0);
When building, causes:
CCHLinkTextView.h:41:43: Auto property synthesis will not synthesize property 'linkTextAttributes'; it will be implemented by its superclass, use @dynamic to acknowledge intention

**Comment by choefele** [comment]
Fixed in 680f783196dbcf4e03b60cf29dfdb9e7a5a2fd0b
