### ISSUE TITLE
TextView default copy/paste menu don't open on long press

### ISSUE THREAD

**Issue by zeevvax** [choefele/CCHLinkTextView#11]
When long pressing a link the menu does open, but pressing anywhere else in the textView will not open a the copy/paste menu.

I tried to workaround this by adding long press to view below the text view (in this case the contentView of a UICellView). I could get the long press gesture to work, but trying to open the menu didn't work.

**Comment by choefele** [comment]
Copy & Paste interferes with long tap – I'm surprised this works with links. It might be possible to implement a property to disable the long tap detection. Another option would be to trigger an action sheet on long tap with copy options (that's what Twitterrific does).

**Comment by choefele** [comment]
Thanks for reporting this issue. If you want to look into fixing it, I'd be happy to have a look at a PR. At the moment, I consider this a known limitation of the library.
