### ISSUE TITLE
Tap to copy text

### ISSUE THREAD

**Issue by peterpaulis** [choefele/CCHLinkTextView#18]
Is there a way to enable the copy text functionality? as CCHLinkTextView seems to block this

**Comment by choefele** [comment]
The way I do it is to copy the entire table cell's content on long tap (this is also how Twitterrific does it). You can also experiment with setting `selectable` to `YES`.

**Comment by peterpaulis** [comment]
selectable doesn't seems to have an effect... how do you listen for the long tap?

**Comment by choefele** [comment]
Here is an example: https://github.com/Stolpersteine/stolpersteine-ios/blob/master/Stolpersteine/iPhone/StolpersteinCardCell.m#L129

**Comment by peterpaulis** [comment]
i enabled selection and also detecting the tap / long press on normal text (so you don't need to add another gesture recognizer)

https://github.com/choefele/CCHLinkTextView/pull/19

**Comment by choefele** [comment]
Thanks for your pull request. I'm not sure registering the long press on the text view is very useful. I would usually register it on the `UITableViewCell` so that the entire cell can be used as a tap target (instead of just the area that's occupied by the text view).

**Comment by peterpaulis** [comment]
but the cell can contain more content, like a image and text and a longpress on the text can present a share or select all for example... i did used it a new update of a news application... as there is already a mechanics in the textview to register a non link click, its always better to make use of it, as to pollute the code... the whole new feature is completely optional, both for press and longpress

**Comment by choefele** [comment]
The additional APIs make this library more complex and harder to understand. In addition, I believe that the functionality your are suggesting can be added by users of this library without any modification of the library itself. This is preferable to adding more features IMHO.

**Comment by peterpaulis** [comment]
but you have to add another recognizer and make sure it doesn't get conflicted with the text view... this doesn't add more complexity, just opens more ways how to use the component (the added code is just about exposing functionality, which was essentially already there)

**Comment by choefele** [comment]
Sorry, but I would like to keep this library as focused as possible

**Comment by peterpaulis** [comment]
a pity, this doesn't take the focus, just enables to do more with little than no code overhead
