### ISSUE TITLE
Tap gesture recognized on two different links

### ISSUE THREAD

**Issue by Jonge** [choefele/CCHLinkTextView#7]
Hi,

I have a minor problem with this library. When two links are close to each other (in my case one above the other, but not overlapping), it is possible for the library to detect the tap on two different links, resulting in unexpected behavior.

To replicate the issue, just use a `CCHLinkTextView` with an attributed text using font `[UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline]` and a few links.

See attached image. When you perform a tap gesture between the links, both of them get recognized.

![ios simulator screen shot 12 2 2015 17 05 37](https://cloud.githubusercontent.com/assets/1653538/6171167/87794858-b2d9-11e4-921a-2694cff827ee.png)

**Comment by choefele** [comment]
Perhaps you can use `tapAreaInsets` to adjust the additional tap area of the link text? `CCHLinkTextView` supports [debug quick look](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/CustomClassDisplay_in_QuickLook/Introduction/Introduction.html) to visualize the tap area.
