### ISSUE TITLE
Tap linked stayed gray after a tap and not calling the delegate

### ISSUE THREAD

**Issue by zeevvax** [choefele/CCHLinkTextView#9]
First I want to say this is a great utility, really improve usability.
The issue is due to the fact I used larger fonts (18 points). So when I tap on the link, it takes less space on the screen. If the tap is a bit longer and at the end of the link, when the tap finish it is no longer identified to be on the link, and there for don't restore it back to original size and don't call the delegate.
   
A simple work around the issue was to set the font size in the linkTextTouchAttributes to the same size.
I think a simple fix to the issue could be enforcing the same font size as the linkTextAttributes.

**Comment by choefele** [comment]
Thanks for your report. Could you please provide a sample project that demonstrates this problem? Thanks again

**Comment by zeevvax** [comment]
In your sample code "ViewController.m" at line 53 add 
    tableViewCell.textView.linkTextAttributes = @{
                                         NSFontAttributeName: [UIFont systemFontOfSize:20],
                                     };
Then when you click on the link at the end you'll see it.

The work around I have for that is setting 
linkTextTouchAttributes = @{
                                          NSFontAttributeName: [UIFont systemFontOfSize:20],
};
